cloud:
  aws:
    credentials:
      access-key: ASIAX22MGECDWUG45IUM
      secret-key: DEvQVdxn5sDYiNpz/aOeHgzBnI5uZoMUtqrmdCSv
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: elasticbeanstalk-us-east-1-538641309831Info


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8083
