cloud:
  aws:
    credentials:
      access-key: ASIAZKA7KBEXKCJ72I5M
      secret-key: N/hNgyNPyIjJsv4FHnH+dv2nY5zIhfwxbZUhcwRp
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: elasticbeanstalk-us-east-1-538641309831Info


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8083
